import "@ant-design/v5-patch-for-react-19";
import Providers from "@components/common/Providers";
import "antd/dist/reset.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "simplebar-react/dist/simplebar.min.css";
import "../../public/styles/index.css";

const inter = Inter({ subsets: ["latin"] });
interface LangLayoutProps {
    children: React.ReactNode;
    params: Promise<{
        lang: string;
    }>;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: LangLayoutProps) {
    // const token = (await cookies()).get("token")?.value;
    const { lang } = await params;

    return (
        <html>
            <body className={inter.className} lang={lang}>
                <NextTopLoader
                    color="#2299DD"
                    crawl={true}
                    crawlSpeed={200}
                    easing="ease"
                    height={2}
                    initialPosition={0.08}
                    shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                    showAtBottom={false}
                    showSpinner={false}
                    speed={200}
                    zIndex={1600}
                />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
