import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body className={inter.className}>
                <NextTopLoader
                    color="#2299DD"
                    crawl={true}
                    crawlSpeed={200}
                    easing="ease"
                    height={2}
                    initialPosition={0.08}
                    shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                    showAtBottom={false}
                    showSpinner={false}
                    speed={200}
                    zIndex={1600}
                />
                {children}
            </body>
        </html>
    );
}
