import Layouts from "@ui/Layouts";
import Providers from "@ui/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LangLayoutProps {
    params: Promise<{
        lang: string;
    }>;
    children: React.ReactNode;
}

export default async function LangLayout({ children, params }: Readonly<LangLayoutProps>) {
    const { lang } = await params;
    return (
        <html lang={lang}>
            <body className={inter.className}>
                <Providers>
                    <Layouts>{children}</Layouts>
                </Providers>
            </body>
        </html>
    );
}
