const iconPacks: Record<string, () => Promise<any>> = {
    Ai: () => import("react-icons/ai"),
    Bi: () => import("react-icons/bi"),
    Bs: () => import("react-icons/bs"),
    Cg: () => import("react-icons/cg"),
    Ci: () => import("react-icons/ci"),
    Di: () => import("react-icons/di"),
    Fa6: () => import("react-icons/fa6"),
    Fa: () => import("react-icons/fa"),
    Fc: () => import("react-icons/fc"),
    Fi: () => import("react-icons/fi"),
    Gi: () => import("react-icons/gi"),
    Go: () => import("react-icons/go"),
    Gr: () => import("react-icons/gr"),
    Hi2: () => import("react-icons/hi2"),
    Hi: () => import("react-icons/hi"),
    Im: () => import("react-icons/im"),
    Io5: () => import("react-icons/io5"),
    Io: () => import("react-icons/io"),
    Lia: () => import("react-icons/lia"),
    Lu: () => import("react-icons/lu"),
    Md: () => import("react-icons/md"),
    Pi: () => import("react-icons/pi"),
    Ri: () => import("react-icons/ri"),
    Rx: () => import("react-icons/rx"),
    Si: () => import("react-icons/si"),
    Sl: () => import("react-icons/sl"),
    Tb: () => import("react-icons/tb"),
    Tfi: () => import("react-icons/tfi"),
    Ti: () => import("react-icons/ti"),
    Vsc: () => import("react-icons/vsc"),
    Wi: () => import("react-icons/wi"),
};

export default iconPacks;
